trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:

- script: |
    node --version
    npm --version
  displayName: 'Environment Check'

- script: |
    npm ci
  displayName: 'Install Dependencies'

- script: |
    npm test
  displayName: 'Run Tests'

- script: |
    docker --version
    docker build -t nodejs-docker-devops:latest .
  displayName: 'Docker Build'