trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    node --version
    npm --version
  displayName: 'Environment Check'

- script: |
    npm ci
  displayName: 'Install Dependencies'

- script: |
    npm test
  displayName: 'Run Tests'

- script: |
    docker --version
    docker build -t nodejs-docker-devops:latest .
  displayName: 'Docker Build'

- task: Docker@2
  displayName: 'Docker Build and Push'
  inputs:
    command: buildAndPush
    repository: rohanqamar/nodejs-docker-devops
    dockerfile: '**/Dockerfile'
    containerRegistry: 'dockerhub-connection'
    tags: |
      latest